spring.datasource.url=jdbc:postgresql://localhost:5432/BonecosDePilao
spring.datasource.username=postgres
spring.datasource.password=Kek@0331
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database=postgresql
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

server.port=8080
